- name: Repository Dispatch
  uses: peter-evans/repository-dispatch@v1.1.1

    with:
    # A repo scoped GitHub Personal Access Token
    token: ${{ secrets.REPO_ACCESS_TOKEN }}
    # The full name of the repository to send the dispatch.
    repository: rickrain/actions-test

    
