name: Do Something That Needs Scheduled

on:
  repository_dispatch:
    types: action-1
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: ubuntu-latest
    steps:
      - name: Do Something
        run: echo Doing Something...
