name: Do Something That Needs Scheduled

on:
  repository_dispatch:
    types: trigger-action-1
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  build:
    name: Run Some Scheduled Thing
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.1

      - name: Do Something
        run: echo Doing Something...
